receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  logging:
  prometheus:
    endpoint: "otelcol:9464"
  otlphttp:
    endpoint: "https://collector.heliosphere.io"
    traces_endpoint: "https://collector.heliosphere.io/traces"
    headers:
      Authorization: "27ffbd45c6943160c03f"


processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
