receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  logging:
  prometheus:
    endpoint: "otelcol:9464"
  otlphttp:
    endpoint: "https://collector.heliosphere.io"
    traces_endpoint: "https://collector.heliosphere.io/traces"
    headers:
      Authorization: "DEMO_HS_TOKEN"

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [spanmetrics, batch]
      exporters: [logging, otlp, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
