name: "Run OpenTelemetry demo"

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: docker compose build otelcol && docker compose up --no-build
